<a href="https://colab.research.google.com/github/cardstud/DS-Unit-1-Sprint-3-Statistical-Tests-and-Experiments/blob/master/ZstatisticsVideoNotes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Getting the WEIGHTED MEAN

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### WEIGHTED MEAN

In [0]:
# Calculate weighted average mark
data = {'Subject': ['Probability and Distributions', 'Statistical Inference', 'Regression I', 'Regression II'], 'Mark': [65, 81, 78,76], 'Credit Points':[4,4,6,6]}
df= pd.DataFrame(data)

In [0]:
#data = {'Subject': ['Probability and Distributions', 'Statistical Inference', 'Regression I', 'Regression II'], 'Mark': [65, 81, 78,76], 'Credit Points':[4,4,6,6]}
df= pd.DataFrame(data={'Subject': ['Probability and Distributions', 'Statistical Inference', 'Regression I', 'Regression II'], 'Mark': [65, 81, 78,76], 'Credit Points':[4,4,6,6]})
df

Subject  Mark  Credit Points
0  Probability and Distributions    65              4
1          Statistical Inference    81              4
2                   Regression I    78              6
3                  Regression II    76              6

In [0]:
# Doing a check to see if mean came out right manually
(65*4) + (81*4) + (78*6) + (76*6)

1508

In [0]:
1508 / 20

75.4

In [0]:
df.describe()

Mark  Credit Points
count   4.00000       4.000000
mean   75.00000       5.000000
std     6.97615       1.154701
min    65.00000       4.000000
25%    73.25000       4.000000
50%    77.00000       5.000000
75%    78.75000       6.000000
max    81.00000       6.000000

In [0]:
# One way to get mean of this dataset
df.groupby(df['Subject']).apply(lambda x: np.average(df['Mark'], weights=df['Credit Points']))

Subject
Probability and Distributions    75.4
Regression I                     75.4
Regression II                    75.4
Statistical Inference            75.4
dtype: float64

In [0]:
# Another way
weighted = (df['Mark']*df['Credit Points']).sum()/df['Credit Points'].sum()

In [0]:
weighted

75.4

In [0]:
# Change index to Subject
df1 = df.set_index(['Subject'])
df1

Mark  Credit Points
Subject                                           
Probability and Distributions    65              4
Statistical Inference            81              4
Regression I                     78              6
Regression II                    76              6

In [0]:
# Calculate weighted mean of the df
weighted = (df1['Mark']*df1['Credit Points']).sum()/df1['Credit Points'].sum()

In [0]:
weighted

75.4

In [0]:
# Another example
df = pd.Series([1.98, 2.03, 2.11, 2.16, 1.88], index = ['X1', 'X2', 'X3', 'X4', 'X5'])
df

X1    1.98
X2    2.03
X3    2.11
X4    2.16
X5    1.88
dtype: float64

In [0]:
df.mean()

2.032

### GEOMETRIC MEAN - commonly used with rates of return

In [0]:
# My tesla stock gained 10% in Year 1, 20% in Year 2 and 30% in Year 3.
#     What is the average yearly rate of return?

In [0]:
#from statistics import geometric_mean
from scipy import stats

In [0]:
yearly_return = pd.DataFrame({'Year':[100, 110, 132, 171.60], 'Rate of Return': [100.0, 110.0, 132.0, 171.6]})
yearly_return

Year  Rate of Return
0  100.0           100.0
1  110.0           110.0
2  132.0           132.0
3  171.6           171.6

In [0]:
h = stats.gmean(yearly_return)

In [0]:
h

array([125.63798861, 125.63798861])

In [0]:
# Column wise =     scipy.stats.gmean(df.iloc[:,1:3],axis=0)
# Specific column = scipy.stats.gmean(df.loc[:,"Score1"])
# Row wise =        scipy.stats.gmean(df.iloc[:,1:3],axis=1)

In [0]:
#scipy.stats.gmean(df.iloc[:,1:3],axis=0)
h = stats.gmean(yearly_return.iloc[:, 1], axis=0)

In [0]:
h

125.63798860573131

In [0]:
# Answer should be 1.1972, remove one so .19 or 19% 

### HARMONIC MEAN - commonly used with rates

In [0]:
# I swim one minute of freestyle at 3 km/h, then one minute of breaststroke at 2 km/h. -- fixed time
#     What is my average speed

In [0]:
# Distance/time --> Average across Fixed time --> Arithmetic mean because it is about fixed time (denominator of distance/time)

In [0]:
df = pd.DataFrame(data={'Style': ['freestyle', 'breastsroke'], 'Time': [1, 1], 'Speed (km/h)': [3, 2]})

In [0]:
df

Style  Time  Speed (km/h)
0    freestyle     1             3
1  breastsroke     1             2

In [0]:
# Arithmetic mean
df.mean()

Time            1.0
Speed (km/h)    2.5
dtype: float64

In [0]:
# Now, if i swim one lap of freestle at 3 km/h then
#   one lap of breaststroke at 2 km/h.
# What is average speed

# Difference here is that I am swimming a longer lap at 2 km/h so no longer arithmetic mean - fixed distance
# Distance/time --> Average across distance --> Harmonic Mean - this is about fixed distance (numerator of distance/time)

In [0]:
df1 = pd.DataFrame(data={'Style': ['freestyle', 'breastsroke'], 'Lap': [1, 1], 'Speed (km/h)': [3, 2]})

In [0]:
df1

Style  Lap  Speed (km/h)
0    freestyle    1             3
1  breastsroke    1             2

In [0]:
df2 = df1.set_index(['Style'])
df2

Lap  Speed (km/h)
Style                         
freestyle      1             3
breastsroke    1             2

In [0]:
# Column wise     = scipy.stats.hmean(df.iloc[:,1:3],axis=0)
# Specifi column  = scipy.stats.hmean(df.loc[:,"Score1"])
# Row wise        = scipy.stats.hmean(df.iloc[:,1:3],axis=1)

In [0]:
g = stats.hmean(df2.iloc[:, "Speed"])

In [0]:
# Answer should be 2.4

### MEDIAN

- Definition: The median is the middle number of the series when ordered

In [0]:
# Odd set of numbers - just take middle of the ordered list
g = pd.Series([10,28,28,53,54])
g

0    10
1    28
2    28
3    53
4    54
dtype: int64

In [0]:
g.median()

28.0

In [0]:
# Even set of numbers - take average of the 2 middle numbers
h = pd.Series([10,28,28,33,54,59])
h

0    10
1    28
2    28
3    33
4    54
5    59
dtype: int64

In [0]:
h.median()

30.5

### MEAN vs MEDIAN
- Symmetric distributions (Bell curve, bimodal distribution) - here the mean will be roughy equal to median
- Asymmetric distributions (skewed distributions) -  wherever median is, the mean will be somewhat higher

In [0]:
# Which is more representative of this series, mean or median?
a = pd.Series([10, 28, 28, 33, 540])
a

0     10
1     28
2     28
3     33
4    540
dtype: int64

In [0]:
a.mean()

127.8

In [0]:
a.median()

28.0

In [0]:
# So which is more reflective of the central tendency of this set? Clearly its the 28, not 127.8
#    So median is more representative of a skewed dataset, particularly when its heavily skewed

### MODE
- Definition: The observation with the highest frequency
- Small sample: Mode is not a good representation
- Large sample: Mode is good

In [0]:
import statistics
import pandas as pd

In [0]:
b = pd.Series([10,28,28,33,54])
b

0    10
1    28
2    28
3    33
4    54
dtype: int64

In [0]:
b.mode()

0    28
dtype: int64

In [0]:
# Mode is quite fickle..below could say no mode or alternatively could say there are 5 modes each with a frequency of 1
c = pd.Series([10,27,28,33,54])
c

0    10
1    27
2    28
3    33
4    54
dtype: int64

In [0]:
# No duplicate values so all are the mode with a frequency of 1
c.mode()

0    10
1    27
2    28
3    33
4    54
dtype: int64

In [0]:
# Small sample - mode is not good representation 
d = pd.Series([10,27,28,54,54])
d

0    10
1    27
2    28
3    54
4    54
dtype: int64

In [0]:
d.mode()

0    54
dtype: int64

In [0]:
# is 54 a great representation of this dataset?
#   No, mode is bad in small datasets

In [0]:
# Decent size dataset
# How many children in your family - census in Australia asked this
df = pd.Series( [1.5, 1.8, 1.0, 0.4, 0.2, 0.1], index=['1', '2', '3', '4', '5', '6+'])
df

1     1.5
2     1.8
3     1.0
4     0.4
5     0.2
6+    0.1
dtype: float64

In [0]:
df.mode()

0    0.1
1    0.2
2    0.4
3    1.0
4    1.5
5    1.8
dtype: float64

In [0]:
d.mean()

34.6

In [0]:
d.median()

28.0

In [0]:
df1 = pd.DataFrame(data={'Kids':[1,2,3,4,5,6], 'Families':[1.5, 1.8, 1.0, 0.4, 0.2, 0.1]})
df1

Kids  Families
0     1       1.5
1     2       1.8
2     3       1.0
3     4       0.4
4     5       0.2
5     6       0.1

In [0]:
df1.mode()

Kids  Families
0     1       0.1
1     2       0.2
2     3       0.4
3     4       1.0
4     5       1.5
5     6       1.8

In [0]:
df.median()

0.7

In [0]:
df.mean()

0.8333333333333334

In [0]:
#df.loc[:,"Score1"].mode()
df1.loc[:, "Kids"].mode()

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [0]:
df1.loc[:, "Kids"].mean()

3.5

### Positively Skewed
- mode < median < mean


### QUANTILES - just a way to split the datasetup into parts
## 2 ways: one to include median, other to exclude. If dataset is large, wont matter.
- Quartiles (into quarters)
- Deciles (into tenths)
- Percentiles (into 100ths)

In [0]:
import numpy as np
# Ordered dataset
x = np.arange(4, 190)

In [0]:
x

array([  4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,
        17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
        30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
        56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
        69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
       108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
       121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
       134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
       147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159,
       160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
       173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 18

In [0]:
df = pd.DataFrame(data=x)
df.head()

0
0  4
1  5
2  6
3  7
4  8

In [0]:
# How to describe the dataset
df.max()

0    189
dtype: int64

In [0]:
df.min()

0    4
dtype: int64

In [0]:
df.mean()

0    96.5
dtype: float64

In [0]:
df.median()

0    96.5
dtype: float64

In [0]:
df.mode()

In [0]:
# The first quartile is the observation that is one quarter of the way through the ordered dataset
# The second quartile would be the median (it's two quarters through dataset)
# The third quartile would be the htird quarter of the ordered dataset (is 3 quarters through the dataset)
# The fourth quartile is the last quarter of the dataset


In [0]:
# Decile splits the dataset into 10ths (whereas quartile splits it into quarters)
# The first decile is the observation that is one thenth of the way through the dataset
# The 2nd decile is two-tenths through the dataset (and so on)

In [0]:
# Percentiles split the dataset into 100ths
# The first percentile is one percent of the way through the dataset
# The second percentile is two percent of the way through the dataset(and so on)

In [0]:
# Example
x = pd.Series([2,2,5,6,9,10,13])

In [0]:
x

0     2
1     2
2     5
3     6
4     9
5    10
6    13
dtype: int64

In [0]:
# Find the five number summary (Min, Q1, Q2, Q3, Max) for the series above
x.min()

2

In [0]:
x.max()

13

In [0]:
x.median() # which is Q2

6.0

In [0]:
x.mean()

6.714285714285714

In [0]:
x.quantile([0.25, .5, .75])

0.25    3.5
0.50    6.0
0.75    9.5
dtype: float64

In [0]:
x.describe()

count     7.000000
mean      6.714286
std       4.151879
min       2.000000
25%       3.500000
50%       6.000000
75%       9.500000
max      13.000000
dtype: float64

### RANGE AND INTERQUARTILE RANGE (IQRs)
- Range is the measure of the spread of a dataset. It is the maximum - the minimum value
- IQR is the 3rd quartile minus the 1st quartile (Q3 - Q1 = IQR)

In [0]:
x = pd.DataFrame(data= [2,2,5,6,9,10,58])
x

0
0   2
1   2
2   5
3   6
4   9
5  10
6  58

In [0]:
x.quantile([0.5])

0
0.5  6.0

In [0]:
q75, q25 = np.percentile(x, [75 ,25])
iqr = q75 - q25

In [0]:
iqr

6.0

In [0]:
q75 = np.percentile(x, [25])
q75

array([3.5])

In [0]:
# Big spread doesnt hurt the IQR where the outlier could change greatly the range

### VARIANCE AND STANDARD DEVIATION
- Variance is the average squared deviation from the population mean
- Standard Deviation


In [0]:
# Weekly expenditure on  petrol
df = pd.DataFrame(data={'Week': [1,2,3,4,5,6,7,8,9,10,11,12], 'Expenditure': [48.50, 87.40, 19.98, 59.74, 40.87, 105.51, 40.80, 23.10, 98.10, 60.54, 64.81, 48.01]})
df

Week  Expenditure
0      1        48.50
1      2        87.40
2      3        19.98
3      4        59.74
4      5        40.87
5      6       105.51
6      7        40.80
7      8        23.10
8      9        98.10
9     10        60.54
10    11        64.81
11    12        48.01

In [0]:
df.mean()

Week            6.500000
Expenditure    58.113333
dtype: float64

In [0]:
df.var()

Week            13.000000
Expenditure    748.011697
dtype: float64

In [0]:
df.std()

Week            3.605551
Expenditure    27.349803
dtype: float64

In [0]:
# Why do we bother with variance (why do we square stuff?)
#    Objective: describe the spread of the dataset, the variance
#         Could use Range but that can be distorted by outliers
#         Could use finding average deviation of the mean, problem is the sum of the negative and positive will equal out and you wil get zero   
#         Could take that absolute values of the deviations but not good to do
#         Best is to take the average squared deviation from the mean, which is the variance

# Why do we divide by n-1
#    We wont know where the population mean is so best is to estimate where it is uing the sample mean
#    The sample mean is just one POSSIBLE position for the true population mean, mu., at any other position, the sum of squares would be larger
#       So we need to take account of that otherwise our estimate of the true variance will be less than it is.
#       The smaller denomimator adjusts the variance estimate upwards
